#define kItemAlias @"alias"
#define kItemPath @"path"
#define kItemBaseBundle @"baseBundle"
#define kItemName @"name"
#define kItemDescription @"description"
#define kItemChildren @"children"
#define kItemID @"ID"
#define kItemEnabled @"enabled"
#define kItemModificationDate @"modificationDate"
#define kItemSettings @"settings"
#define kItemSource @"source"
#define kItemIcon @"icon"

#define kItemFileContents @"fileContents"
#define kItemFolderTypes @"folderTypes"
#define kItemFolderDepth @"folderDepth"
#define kItemExcludeFiletypes @"excludeFiletypes"
#define kItemDescendIntoBundles @"descendIntoBundles"
#define kItemParser @"parser"
#define kItemScanContents @"scanContents"
#define kItemSkipItem @"skipItem"

#define QSDirectObjectIconProxy @"QSDirectObjectIconProxy"

#define mainWindowKey @"mainWindow"
