name: Bug Report
description: Submit a report for an issue you're having with Quicksilver
title: "[Bug]: "
labels: ["Needs Review"]
body:
  - type: checkboxes
    id: before-posting
    attributes:
      label: "Before submitting your bug report, please confirm you have completed the following steps"
      description: All steps are **required**. Your issue may be closed if not.
      options:
        - label: Searched the issue is not already listed in the [Issue List](https://github.com/quicksilver/Quicksilver/issues?q=is%3Aissue) (I've searched it)
          required: true
        - label: Searched in the [Quicksilver Users' Group](https://groups.google.com/forum/#!forum/blacktree-quicksilver) for questions relating to tech support.
          required: true
        - label: Downloaded the [latest version of Quicksilver](https://qsapp.com/) for your system and confirmed the issue still persists.
          required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug description
      description: |
        Provide a clear, concise description of the bug you're experiencing.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: Steps to reproduce
      description: |
        Describe the steps to reproduce the bug.
        The better your description is, the faster we'll be able to help solve your issue. 
      value: |
        1.
        2.
        3.
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: Describe what you expected to happen instead.
    validations:
      required: true
  - type: dropdown
    id: macos-version
    attributes:
      label: MacOS Version
      description: |
        Select the macOS version you are using
        _Describe in the "Additional info" section if you chose "Other"._
      options:
        - macOS 12
        - macOS 11
        - macOS 10.15
        - macOS 10.14
        - Other
  - type: input
    id: qs-version
    attributes:
      label: Quicksilver Version
      description: Type the version of Quicksilver you are using
  - type: textarea
    id: plugins
    attributes:
      label: Relevant Plugins
      description: Ener a list of any plugins and their versions relevant to this issue. You can view a list of your [installed plugins here](qs://preferences#QSPlugInsPrefPane)
  - type: textarea
    id: crash-hang
    attributes:
      label: Crash Logs or Spindump
      description: |
        * Crash Report: Please upload a crash log from Console.app.
        * Hang Report: Please upload a spindump log. You can obtain a spindump by following [these steps](https://support.zoom.us/hc/en-us/articles/206435255-Creating-a-Spindump-file-on-macOS) but selecting 'Quicksilver' in Step 5.
  - type: textarea
    id: screenshot
    attributes:
      label: Screenshots
      description: Please provide screenshots that illustrate your bug.
  - type: textarea
    id: additional-info
    attributes:
      label: Additional info
      description: |
        Any additional information related to the issue (e.g. Console.app errors, other conflicting software, computer/keyboard language).