/*
 *     Generated by class-dump (version 2.1.5).
 *
 *     class-dump is Copyright (C) 1997, 1999, 2000, 2001 by Steve Nygard.
 */

/*
 * File: /System/Library/PrivateFrameworks/SystemUIPlugin.framework/Versions/A/SystemUIPlugin
 */

#import <AppKit/AppKit.h>

@interface NSMenuExtra:NSStatusItem
{
    NSBundle *_bundle;
    NSMenu *_menu;
    NSView *_view;
    float _length;
    struct  {
      int customView:1;
      int menuDown:1;
      int reserved:30;
    } _flags;
    id _controller;
}

- initWithBundle:fp8;
- initWithBundle:fp8 data:fp12;
- (void)willUnload;
- (void)dealloc;
- bundle;
- (float)length;
- (void)setLength:(float)fp8;
- image;
- (void)setImage:fp8;
- alternateImage;
- (void)setAlternateImage:fp8;
- menu;
- (void)setMenu:fp8;
- toolTip;
- (void)setToolTip:fp8;
- view;
- (void)setView:fp8;
- (char)isMenuDown;
- (void)drawMenuBackground:(char)fp8;
- (void)popUpMenu:fp8;
- (void)unload;
- statusBar;
- (SEL)action;
- (void)setAction:(SEL)fp8;
- target;
- (void)setTarget:fp8;
- title;
- (void)setTitle:fp8;
- attributedTitle;
- (void)setAttributedTitle:fp8;
- (char)isEnabled;
- (void)setEnabled:(char)fp8;
- (void)setHighlightMode:(char)fp8;
- (char)highlightMode;
- (void)sendActionOn:(int)fp8;
- _initInStatusBar:fp8 withLength:(float)fp12 withPriority:(int)fp16;
- _window;
- _button;
- (void)_adjustLength;

@end

@interface NSMenuExtra(NSMenuExtraPrivate)
+ (unsigned int)defaultLength;
- (void)setController:fp8;
- (void)setMenuDown:(char)fp8;
- (float)defaultLength;
@end

@interface NSDockExtra:NSObject
{
    NSBundle *_bundle;
    unsigned int _id;
    void *_nativeWindow;
    id _controller;
    struct{
      int nativeWindow:1;
      int reserved:31;
    } _flags;
    long _fReserved1;
    long _fReserved2;
    long _fReserved3;
    long _fReserved4;
}

- initWithBundle:fp8;
- initWithBundle:fp8 data:fp12;
- (void)dealloc;
- (void)willUnload;
- bundle;
- menu;
- (void)toggle;
- (void)handleMenuCommand:(unsigned int)fp8 tag:(unsigned int)fp12;
- (void)setDockLabel:fp8;
- cocoaWindow;
- (void *)carbonCGrafPtr;

@end

@interface NSDockExtra(NSDockExtraReallyPrivate)
- (void)_releaseWindow;
@end

@interface NSDockExtra(NSDockExtraPrivate)
- initWithBundle:fp8 identifier:(unsigned int)fp12 controller:fp16;
- initWithBundle:fp8 identifier:(unsigned int)fp12 data:fp16 controller:fp20;
- (void *)cgWindow;
@end

@interface NSMutableArray(NSDockExtraMenu)
- (void)insertItem:fp8 atIndex:(int)fp12;
- (void)addItem:fp8;
- insertItemWithTitle:fp8 action:(SEL)fp12 atIndex:(int)fp16;
- addItemWithTitle:fp8 action:(SEL)fp12;
- (void)removeItemAtIndex:(int)fp8;
- (void)setSubmenu:fp8 forItem:fp12;
- (int)indexOfItemWithTitle:fp8;
- (int)indexOfItemWithAction:(SEL)fp8;
- itemWithTitle:fp8;
- itemWithAction:(SEL)fp8;
@end

@interface NSMutableDictionary(NSDockExtraMenuItem)
+ separatorItem;
+ itemWithTitle:fp8 action:(SEL)fp12;
- (char)hasSubmenu;
- (void)setSubmenu:fp8;
- submenu;
- (void)setSubmenuSelectable:(char)fp8;
- (char)isSubmenuSelectable;
- (void)setTitle:fp8;
- title;
- (char)isSeparatorItem;
- (void)setEnabled:(char)fp8;
- (char)isEnabled;
- (void)setAction:(SEL)fp8;
- (SEL)action;
- (void)setTag:(int)fp8;
- (int)tag;
- (void)setMark:(int)fp8;
- (int)mark;
- (void)setMarkChar:fp8;
- markChar;
- (void)setHeader:(char)fp8;
- (char)isHeader;
- (void)setStyle:(int)fp8;
- (int)style;
- (void)setIndent:(unsigned short)fp8;
- (unsigned short)indent;
- (void)setDynamicMask:(int)fp8;
- (int)dynamicMask;
- (void)removeDynamicMask;
- (void)setDynamicBreak:(char)fp8;
- (char)dynamicBreak;
- (void)setSystemIcon:(unsigned int)fp8;
- (unsigned int)systemIcon;
- (void)setResourceIcon:fp8;
- resourceIcon;
- (void)setIconEnabled:(char)fp8;
- (char)isIconEnabled;
@end

@interface NSApplicationDockExtra:NSDockExtra
{
}

- (void)applicationLaunched;
- (void)applicationDied;
- (void)setDockLabel:fp8;

@end

@interface NSMenuExtraView:NSView
{
    NSMenu *_menu;
    NSMenuExtra *_menuExtra;
    NSImage *_image;
    NSImage *_alternateImage;
}

- initWithFrame:(NSRect)fp12 menuExtra:fp28;

- (void)dealloc;
- (void)setMenu:fp8;
- image;
- (void)setImage:fp8;
- alternateImage;
- (void)setAlternateImage:fp8;
- (void)drawRect:(NSRect)fp12;
- (void)mouseDown:fp8;

@end

