name: sign

on:
  push:
    tags:
      - "v*.*.*"
  pull_request:

jobs:
  build:
    runs-on: macos-11
    env:
      MACOS_CERTIFICATE: ${{ secrets.MACOS_CERTIFICATE }}
      MACOS_CERTIFICATE_PASSWORD: ${{ secrets.MACOS_CERTIFICATE_PASSWORD }}
      KEYCHAIN_PASSWORD: ${{ secrets.KEYCHAIN_PASSWORD }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - run: |
        # https://docs.github.com/en/actions/deployment/deploying-xcode-applications/installing-an-apple-certificate-on-macos-runners-for-xcode-development
        KEYCHAIN_PATH=${RUNNER_TEMP}/app-signing.keychain-db
        CERTIFICATE_PATH=${RUNNER_TEMP}/build_certificate.p12
        echo -n "${MACOS_CERTIFICATE}" | base64 --decode --output "${CERTIFICATE_PATH}"
        security create-keychain -p "${KEYCHAIN_PASSWORD}" "${KEYCHAIN_PATH}"
        security set-keychain-settings -lut 21600 "${KEYCHAIN_PATH}"

        security unlock-keychain -p "${KEYCHAIN_PASSWORD}" "${KEYCHAIN_PATH}"

        security import "${CERTIFICATE_PATH}" -P "${MACOS_CERTIFICATE_PASSWORD}" -A -t cert -f pkcs12 -k "${KEYCHAIN_PATH}"
        security list-keychain -d user -s "${KEYCHAIN_PATH}"

        cd Quicksilver
        ./Tools/qsrelease
    - name: Upload document
      uses: actions/upload-artifact@v2
      with:
        name: Quicksilver.dmg
        path: /tmp/QS/build/Release/Quicksilver*.dmg
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: /tmp/QS/build/Release/Quicksilver*.dmg
